spring.datasource.url=jdbc:h2:mem:account_transfer
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.h2.console.path=/h2-console
logging.level.liquibase=DEBUG
logging.level.org.springframework.jdbc=DEBUG
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# FX rate
fx.rate.usd-to-eur=0.86

standing-order.scheduler.cron=0 */1 * * * *